/**
 * Abstract card artwork (public/art/*.jpg), generated by
 * scripts/generate-art.mjs. Maps content taxonomy to a consistent
 * visual per category / industry / solution.
 */

const CATEGORY_ART: Record<string, string> = {
  "Data & Analytics": "grid-cyan",
  AI: "torus-violet",
  "Agentic AI": "torus-blue",
  Products: "plexus-blue",
  Consulting: "plexus-violet",
  Retail: "columns-violet",
  Banking: "arcs-teal",
  Insurance: "helix-teal",
  Healthcare: "sphere-teal",
  Manufacturing: "columns-cyan",
  "Telecom & Media": "tunnel-blue",
  "Company news": "ribbon-violet",
};

export function artForCategory(category: string): string {
  return `/art/${CATEGORY_ART[category] ?? "plexus-blue"}.jpg`;
}

/** Hero-resolution (2400x1100) version of a subject's artwork, used as
 *  the full hero background on detail pages. */
export function heroArtForSolution(slug: string): string {
  return `/waves/hero-${SOLUTION_ART[slug] ?? "sphere-blue"}.jpg`;
}

export function heroArtForIndustry(slug: string): string {
  return `/waves/hero-${INDUSTRY_ART[slug] ?? "plexus-blue"}.jpg`;
}

export function heroArtForProduct(slug: string): string {
  return `/waves/hero-${PRODUCT_ART[slug] ?? "plexus-blue"}.jpg`;
}

const INDUSTRY_ART: Record<string, string> = {
  retail: "columns-violet",
  banking: "arcs-teal",
  insurance: "helix-teal",
  healthcare: "sphere-teal",
  manufacturing: "columns-cyan",
  "telecom-media": "tunnel-blue",
};

export function artForIndustry(slug: string): string {
  return `/art/${INDUSTRY_ART[slug] ?? "plexus-blue"}.jpg`;
}

const PRODUCT_ART: Record<string, string> = {
  plexuscore: "grid-cyan",
  plexusiq: "sphere-blue",
  agentmesh: "torus-blue",
};

export function artForProduct(slug: string): string {
  return `/art/${PRODUCT_ART[slug] ?? "plexus-blue"}.jpg`;
}

const SOLUTION_ART: Record<string, string> = {
  "data-analytics": "grid-cyan",
  ai: "torus-violet",
  "agentic-ai": "torus-blue",
  "app-building": "grid-violet",
  "product-building": "ribbon-violet",
};

export function artForSolution(slug: string): string {
  return `/art/${SOLUTION_ART[slug] ?? "sphere-blue"}.jpg`;
}
